### ISSUE TITLE
Make a ystarter-hardhat-kit repo cloned from this one

### ISSUE THREAD

**Issue by storming0x** [storming0x/ystarter-foundry-kit#6]
For the devs that are not familiar with Foundry, HardHat repo allows a wider audience of developers to also work faster with the repo.

**Comment by AlexNi245** [comment]
I created a hardhat fork of this repo that can be found here [here](https://github.com/AlexNi245/ystarter-hardhat-kit).
My goal was to be as close to the original repo as possible so the contracts are the same and the test suite tests the same stuff. 
I also add your yearn-vaults repo as a submodule in order to have solidity 0.8 compliant dependencies.
